# .github/workflows/cpplint.yml
name: C++ Lint

on: [push, pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cpplint
        run: pip install cpplint
      - name: Run cpplint
        run: |
          cpplint --recursive src/ || true

